### ISSUE TITLE
Unable to set Downward Obstacle Brake distance to permitted value

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#122]
Mobile SDK: `5.4`
Drone: Mavic 3E

I have implemented reporting of Obstacle Avoidance presets by using the following:

```
PerceptionManager.getInstance().addPerceptionInformationListener {
            Log.e(TAG, "Perception info updated: ${it.downwardObstacleAvoidanceBrakingDistance}")
            // More reporting...
        }
```

This is working great. I am then attempting to call `PerceptionManager.getInstance().setObstacleAvoidanceBrakingDistance` with a requested distance of 3 meters in the `PerceptionDirection.DOWNWARD` direction. The docs say this is acceptable (accepted range is 0.5 to 3). Upon success, the `PerceptionInformationListener` fires **_twice_**:

```
Perception info updated: 3.0
Perception info updated: 2.0
```

In addition, in the DJI Pilot app, the accepted range is 1.6ft to 6.6ft (or approximately 0.5 meters to 2 meters). Attempts to set the distance to 2.5 are successful but are never reported by the `PerceptionInformationListener`.

I did verify that `ObstacleAvoidanceType` is set to `BRAKE`.

Is the documentation wrong or is this a bug?

**Comment by dji-dev** [comment]
Agent comment from ekho.feng in <a href='https://djisdksupport.zendesk.com/agent/tickets/85819'>Zendesk ticket #85819</a>:<br><br>The problem is that the documentation is faulty, the ranges in the documentation are the ranges given for newer models. We will revise the document later, as for the real range of M3E, you can refer to the range on pilot2. Sorry for the inconvenience
<br><p><em><small>°°°</small></em></p>
