### ISSUE TITLE
Virtual Sticks Position verticalControlMode is not relative to the ground

### ISSUE THREAD

**Issue by timothyolt-dronesense** [dji-sdk/Mobile-SDK-Android-V5#148]
Environment
Drone: DJI Mavic 3 Thermal
Controller:  DJI RC Pro Enterprise
DJI Pilot 2 app version: 7.0.2.2
Mobile SDK version: 5.5.0 (screenshots do include 5.3.0, but retested on 5.5.0 and the same issues persist)
Aircraft Firmware version: 07.00.0102
RC Firmware version: 02.00.0501

Repro steps

- Using the sample app
- Go to Virtual Sticks
- Enable Virtual Sticks and Advanced Virtual Sticks Params
- Set the Virtual Sticks `verticalControlMode` to `POSITION` and the `verticalThrottle` to some AGL number like `20.0`
- Send the Virtual Stick Advanced param
- Aircraft will ascend relative to the aircraft, like `VELOCITY` mode, instead of relative to the ground like `POSITION` mode.
- Sending the command multiple times will move the aircraft again and again, which is also expected to have no effect after the first time

<img width="1628" alt="Screenshot 2023-08-09 at 2 04 53 PM" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/4ec9c0fd-af29-460b-acb2-86fdf7440377">
<img width="1630" alt="Screenshot 2023-08-09 at 2 05 07 PM" src="https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/a5fe3a5b-2e15-4776-8b54-f89c8a0cf4fc">

**Comment by timothyolt-dronesense** [comment]
Also tested on the M30 and Mini 3 Pro, and the same issue appears

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88766'>Zendesk ticket #88766</a>:<br><br>I don't seem to have this issue in my local testing. You can view my test video here:https://pan-sec.djicorp.com/s/TiLWGb8BiGbKQ7q
<br><p><em><small>°°°</small></em></p>

**Comment by timothyolt-dronesense** [comment]
https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/132092688/53819021-4a07-495a-8b1d-34cacc99b9ef

Sorry, put this on the wrong ticket. Yeah, that's exactly how I expected it to work. Here's a video of what I see on the M3T

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/88766'>Zendesk ticket #88766</a>:<br><br>I understand the issue you are referring to based on the video. The behavior shown in the video is normal. The virtual joystick needs to send commands at a certain frequency in order to take effect. Each time you click, it is equivalent to sending a command. The aircraft will not directly ascend to 20 meters.

In POSITION mode, if you set the verticalThrottle to 20, the aircraft will stop ascending after reaching 20 meters, even if the program continues to send commands.
<br><p><em><small>°°°</small></em></p>
