### ISSUE TITLE
MSDK is only partially migrated to AndoidX

### ISSUE THREAD

**Issue by tukez** [dji-sdk/Mobile-SDK-Android-V5#154]
> Task :module-common:kaptGenerateStubsDebugKotlin
WARNING: [Processor] Library '.gradle\caches\modules-2\files-2.1\com.dji\dji-sdk-v5-aircraft-provided\5.5.0\1466986d7f8dd86066402caf3e40486ec3c5220c\dji-sdk-v5-aircraft-provided-5.5.0.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/Nullable'
 Example of support library reference: 'android/support/annotation/Nullable'

SDK 5.5 still contains references to old support library.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/90423'>Zendesk ticket #90423</a>:<br><br>If it does not cause a compilation failure, I think it can be ignored because the content of dji-sdk-v5-aircraft-provided-5.5.0.jar will not be packaged in the apk.
<br><p><em><small>°°°</small></em></p>
