### ISSUE TITLE
Improvements for video decoder YUV data listener interface

### ISSUE THREAD

**Issue by tukez** [dji-sdk/Mobile-SDK-Android-V5#156]
I am trying to stream the video with WebRTC and I'm getting slow downs and frame skips with the video. They do not happen in another software where I'm also streaming with WebRTC (the source is ARCore in this case). This makes me believe the problem might be the massive memory allocations from the DJI video decoder, 90 megabytes per second I think.

Currently the YUV data listener looks like this:

`public interface YuvDataListener {
    void onReceive(MediaFormat mediaFormat, byte[] data, int width, int height);
}`

I think it would be nice for performance reasons to give the data as direct (non heap) ByteBuffer so there is no unecessary memory copying going on. This would need some kind for reference counting interface so the ByteBuffer can be released back to the decoder, same as in Android WebRTC library.

Also some of the information which is available in IVideoFrame would be nice, like the timestamp and fps.

I tried to do the decoding from IVideoFrame myself using the Android MediaCodec but I could not figure out how to setup the decoder parameters. I know its H265 but it seems that alone is not enough for the MediaCodec. Maybe you could provide a sample on how to decode the IVideoFrame data using MediaCodec?

**Comment by GregCornis** [comment]
+1 for direct access to the frame.

It also misses some documentation regarding the format of the data : it seems to be YUV planar, but I believe there is some padding (for the P1 with M350) which is not documented.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/90662'>Zendesk ticket #90662</a>:<br><br>I think it would be nice for performance reasons to give the data as direct (non heap) ByteBuffer so there is no unecessary memory copying going on. This would need some kind for reference counting interface so the ByteBuffer can be released back to the decoder, same as in Android WebRTC library.
-->This part will be optimized in future versions. I have also forwarded your suggestions to our engineers.

I tried to do the decoding from IVideoFrame myself using the Android MediaCodec but I could not figure out how to setup the decoder parameters. I know its H265 but it seems that alone is not enough for the MediaCodec. Maybe you could provide a sample on how to decode the IVideoFrame data using MediaCodec?
-->
I apologize for the inconvenience, but we do not have any sample code for IVideoFrame. In fact, the video stream data obtained by StreamDataListener is missing IDR data in order to reduce the resources occupied by the transmission. Therefore, if you need to obtain video stream data that can be pushed, we recommend using YUV data for re-encoding.

It also misses some documentation regarding the format of the data : it seems to be YUV planar, but I believe there is some padding (for the P1 with M350) which is not documented.
-->The YUV data format we currently provide is YUV420p. However, there are some invalid data in the data that is being pushed to us by some cameras, which results in the size of the data being larger than the resolution multiplied by 1.5. In terms of usage, you can discard the excess parts.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-lyt** [comment]
In the YUV data callback, the mediaformat will display the YUV data format. You can use this format to parse the YUV data.

**Comment by tukez** [comment]
@dji-lyt I think the ticket should be kept open until we have a better interface for observing YUV data?
