### ISSUE TITLE
Connected product info

### ISSUE THREAD

**Issue by PeimanAtaei** [dji-sdk/Mobile-SDK-Android-V5#165]
Hi 

I have implemented the SDK registration method and when the onProductConnect() method calls, we just have the product id.

I want to know how we can find the information of the product line product name.

**Comment by PeimanAtaei** [comment]
this is the solution I found and it works :

![product name](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/80130861/ee5afbd2-7f5e-42b6-abe0-24ac3064582e)

**Comment by Vickyxdev** [comment]
Hi

I am implementing app for mavic 3 ... well all things are working fine except captured media file name. How to get callback method to get file name

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/91918'>Zendesk ticket #91918</a>:<br><br>Please refer to https://sdk-forum.dji.net/hc/en-us/articles/9882782794777-Chapter-10-Media-playback. You can capture media file name through fucntion getFileName()
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
Hi dev

I am asking while capture image i want to know image name and type. how to do that ?

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/91918'>Zendesk ticket #91918</a>:<br><br>I would like to inform you that in order to obtain the file name, it is necessary to retrieve it from MediaManage. When capturing a photo, you have the ability to track the creation of new photos using the KeyNewlyGeneratedMediaFile. This will allow you to obtain the index of the photo. Subsequently, you can utilize mediamanage to retrieve detailed information based on the index of the photo.
<br><p><em><small>°°°</small></em></p>
