### ISSUE TITLE
Captured image info(like Name, type etc.)

### ISSUE THREAD

**Issue by Vickyxdev** [dji-sdk/Mobile-SDK-Android-V5#166]
Hi

I am implementing app for mavic 3 ... well all things are working fine except captured media file name. How to get callback method to get file name

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91989'>Zendesk ticket #91989</a>:<br><br>Currently, the callback provided by the SDK does not allow you to obtain the media file name. You need to obtain the media file first in order to get the name.
<br><p><em><small>°°°</small></em></p>

**Comment by Vickyxdev** [comment]
ok thanks

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91989'>Zendesk ticket #91989</a>:<br><br>I hope this is helpful to you.
<br><p><em><small>°°°</small></em></p>

**Comment by Adityaxdev** [comment]
Hi

I am implementing app for mavic 3 ... well all things are working fine except sensor beep sound not working. How to get callback method for sound beep when any obstacle found ...

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/91989'>Zendesk ticket #91989</a>:<br><br>I understand that you're asking about the sound that Pilot 2 makes when it encounters obstacles. If that's the case, then this is a feature that Pilot 2 itself has implemented.
<br><p><em><small>°°°</small></em></p>
