### ISSUE TITLE
Matrice 300 RTK Sample App Connection Issue: Product Name Displayed as UNKNOWN on Google Pixel 6

### ISSUE THREAD

**Issue by ghost** [dji-sdk/Mobile-SDK-Android-V5#171]
I am in the process of developing a custom app for the Matrice 300 RTK using a Google Pixel 6 for testing. Before diving into the custom app development, I decided to run the sample code provided to understand the basic connectivity and functionalities. However, I am encountering an issue while trying to connect to the remote controller via a USB cable.

Here are the steps I have taken:
1. Installed the sample app on my Google Pixel 6.
2. Connected the phone to the Matrice 300 RTK remote controller using a USB cable.

Upon doing this, I was expecting the Product Name to be displayed correctly, but instead, it consistently shows as "UNKNOWN." I have followed the setup instructions meticulously, and I am unable to figure out the root cause of this issue. 

I'd appreciate any guidance or insights to resolve this problem and establish a successful connection, enabling me to proceed with the custom app development. Thank you!

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/92167'>Zendesk ticket #92167</a>:<br><br>We kindly request your assistance in providing a video recording of your operation process. It would greatly help us in identifying the issue you are experiencing.

Based on your description, it is unclear whether the problem lies with the compatibility of your phone or with your operation. To further investigate, we suggest trying the operation on a different model of mobile phone as well.
<br><p><em><small>°°°</small></em></p>

**Comment by ghost** [comment]
> Agent comment from Hummels Lei in [Zendesk ticket #92167](https://djisdksupport.zendesk.com/agent/tickets/92167):We kindly request your assistance in providing a video recording of your operation process. It would greatly help us in identifying the issue you are experiencing.
> 
> Based on your description, it is unclear whether the problem lies with the compatibility of your phone or with your operation. To further investigate, we suggest trying the operation on a different model of mobile phone as well.
> 
> _°°°_

I am sorry, when I tried connecting it with a different usb cable my problem was fixed, thank you for the reply!!
