### ISSUE TITLE
WaypointAction & WaylineAction

### ISSUE THREAD

**Issue by PeimanAtaeiJPDroni** [dji-sdk/Mobile-SDK-Android-V5#194]
Hi 

I am developing an app and I need to do some actions when I arrive at the waypoints.

In Sample code I realized we have WaypointAction and WaylineAction and for each of them, we have some specific actions.

I searched to find any documentation about these but I did not find.

I need to do these actions when arrive at the first waypoint:

1. stop flying
2. rotate drone
3. rotate gimbal 
4. create folder with a specific name for photos
5. start time interval photo shooting
6. start fly

Please help me which of those classes is correct for me

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/94208'>Zendesk ticket #94208</a>:<br><br>I would like to inform you that in order to generate waypoint mission using MSDK v5, it is necessary to edit kmz files. For detailed information about the kmz file format, I kindly request you to refer to the document available at https://developer.dji.com/cloud-api.
<br><p><em><small>°°°</small></em></p>
