### ISSUE TITLE
V5 FPVWidget

### ISSUE THREAD

**Issue by brizey** [dji-sdk/Mobile-SDK-Android-V5#22]
app:uxsdk_sourceCameraSideVisibility="false" does not set according to property. Side is always displayed.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/67767'>Zendesk ticket #67767</a>:<br><br>You can try to modify FPVWidget_uxsdk_sourceCameraNameVisibility to false, because according to the logic below, the change of SourceCameraSideVisibility does not affect the implementation of the screen.
 ![](https://djisdksupport.zendesk.com/attachments/token/IiKc8cunHGslpxF4dvxggCM8r/?name=image.png)<br><a href='https://djisdksupport.zendesk.com/attachments/token/IiKc8cunHGslpxF4dvxggCM8r' target='zd_attach'>image.png</a>
<br><p><em><small>°°°</small></em></p>
