### ISSUE TITLE
MSDK 5.8.0 how to convert the frame data into JPEG or other image formats

### ISSUE THREAD

**Issue by jeremisty99** [dji-sdk/Mobile-SDK-Android-V5#240]
I noticed that the new version of MSDK has added a frame data acquisition function. According to the Sample project, I implemented downloadYUVImage() to save the frame data to a local file. However, I found that the file was saved successfully but could not be read, and I am not sure what format the file is. If this is normal, could you please advise on how to convert it to JPEG or other image formats for easy handling in the next step?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/98403'>Zendesk ticket #98403</a>:<br><br>The downloadYUVImage only writes YUV frames to the local storage. To view them, you need to use a tool that supports parsing YUV format.

May I ask if it is possible to convert it to JPEG or another image format for easier further processing?"
-->Certainly, you can convert it to JPEG or another format. You can refer to the `newSaveYUVDataToJPEG` method in the sample code. Alternatively, you can capture data in the RGBA_8888 format and then convert it to a bitmap using `bitmap.copyPixelsFromBuffer`. Finally, you can use `bitmap.compress()` to output it as a JPG. Since version 5.8 supports various data formats, you can choose the appropriate conversion method based on your specific needs.
<br><p><em><small>°°°</small></em></p>

**Comment by jeremisty99** [comment]
thanks a lot
