### ISSUE TITLE
Does SDK v5.8.0 need user login to get preview only when used in China

### ISSUE THREAD

**Issue by gangwang2020** [dji-sdk/Mobile-SDK-Android-V5#251]
We have integrated SDK v5.8.0, and only to get preview, do we need login when used in China area

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99336'>Zendesk ticket #99336</a>:<br><br>The interface not being specified as only available in China. It should be effective overseas as well. Did your test results indicate otherwise?
<br><p><em><small>°°°</small></em></p>

**Comment by gangwang2020** [comment]
OK, I already got confirm from DJI RD, no need login for general purpose, please close the ticket.

**Comment by dji-lyt** [comment]
The ticket has closed. Wish you have a good day.
