### ISSUE TITLE
dji::sdk::TimeSyncBase::GetTimeFromApp Crash

### ISSUE THREAD

**Issue by jreedy-riis** [dji-sdk/Mobile-SDK-Android-V5#252]
Hello! We just experienced an MSDK crash with the following Segfault:
```
dji::sdk::TimeSyncBase::GetTimeFromApp
```

Sadly, that is the only information I am able to retrieve about the crash at this time.

We are running the MSDK 5.7.1 on the M350. We are not on the latest firmware (1 behind the latest), but this is the first time we have ever experienced this crash. The MSDK crash has now occurred during multiple flights. After it happened, the MSDK kept throwing the error for about a minute, rendering our Application unusable. After a few minutes, our application became usable again.

One unique piece of information is that the M350 and RC Plus controller normally resides in Central Standard Time, however, at the time of the crash, the drone was flying in Pacific Standard Time. After the crash, the pilot noticed that the controller had the close to the correct clock time, but it did not account for daylight savings (so it was about 1 hour off from the real time in PST). So the pilot manually corrected the time. However, a little bit later the second crash occurred.

So far this issue has occurred twice on us at random times but only today. We are planning to do a factory reset of the controller and updating the firmware of the drone, but is there anything else we can do to avoid this issue?

Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99348'>Zendesk ticket #99348</a>:<br><br>I hope you're doing well. I would like to ask you about the camera you are using. Could you please let us know the make and model of your camera?

Also, regarding the app crash, I would like to clarify if there were any other incidents or events that occurred between the app crash and the plane crash.
<br><p><em><small>°°°</small></em></p>

**Comment by jreedy-riis** [comment]
Hi, sorry just want to clarify the aircraft did not crash, just the MSDK did. The application continuously crashed for a few minutes and then began working again. The camera we were using was an H20T.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99348'>Zendesk ticket #99348</a>:<br><br>Thank you for your clarification. We will verify with our engineers if it is possible that the system time caused the crashes you experienced. If you have more crash logs, we would appreciate it if you could submit them to us.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/99348'>Zendesk ticket #99348</a>:<br><br>I apologize for the long wait. I have confirmed with the engineer that there have been no crashes in MSDK caused by time, and it is unlikely for the code logic to result in crashes due to time. Do you have more complete crash logs and CSDK logs?

CSDK logs are automatically written by the SDK to the software path. They are data records of the underlying operation of the SDK. You can refer to this article for the storage path：https://sdk-forum.dji.net/hc/en-us/articles/7296380174105-How-to-export-the-logs-for-MSDK-V5
<br><p><em><small>°°°</small></em></p>
