### ISSUE TITLE
Vertical mode for surface view

### ISSUE THREAD

**Issue by Conjuror1279** [dji-sdk/Mobile-SDK-Android-V5#254]
I want to use the camera in vertical mode to capture and record the moments for posting on social media, to capture video in the best quality it is required that we get the live stream in vertical mode as well, as this will help us to achieve the best quality shots otherwise its not suitable to look horizontally and record vertical video.

#137

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/99470'>Zendesk ticket #99470</a>:<br><br>We apologize for the inconvenience. At the moment, MSDK does not have any plans to develop the vertical shooting feature for the mini 3. In the future, MSDK will be focusing more on industry-specific applications rather than consumer-level scenarios. Therefore, we regret to inform you that MSDK will not be adapting the vertical shooting feature.
<br><p><em><small>°°°</small></em></p>

**Comment by Conjuror1279** [comment]
Please provide the code for manually processing and rotating the frames, one at a time

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/99470'>Zendesk ticket #99470</a>:<br><br>We apologize for the inconvenience. Unfortunately, the requested service falls outside the scope of our technical support. Regrettably, we are unable to provide the corresponding sample code.
<br><p><em><small>°°°</small></em></p>

**Comment by Conjuror1279** [comment]
Hi Team, 
Could you please propose a solution to this problem, or help us connect with one of your engineering team members who can assist us in this regard? Our work involves purchasing many DJI consumer drones and deploying them at various locations, hence we would be purchasing these drones in massive numbers(even 500+ drones). However, some features are impairing our work and deployment of the drones, causing delays and difficulties in our expansion. Please help us in this regard as we would use the consumer drone category for industry usecases.

Thanking you

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/99470'>Zendesk ticket #99470</a>:<br><br>I would like to inquire about the possible use cases for this feature. Could you please provide some information on why it is necessary for your specific application scenario?
<br><p><em><small>°°°</small></em></p>
