### ISSUE TITLE
I want to use Google Maps with Matrice 350 RTK

### ISSUE THREAD

**Issue by yoshimi-naoyoshi** [dji-sdk/Mobile-SDK-Android-V5#266]
I am currently developing a custom app for Matrice 350 RTK.

I have two questions:

1. Is it possible to connect Android and the remote controller (propo) via USB cable, similar to M300 RTK, and control the drone through the app?
2. When trying to install a custom app using Google Maps within the remote controller, an error message appears stating, "Google Play Developer services are required, but not supported on your device." How can I use Google Maps from the custom app in this case?

I understand it might be inconvenient, but I would appreciate any guidance you can provide. Thank you!

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/100836'>Zendesk ticket #100836</a>:<br><br>The remote control of M350 does not support connecting to other devices via USB. Additionally, the remote control does not support Google Services Framework, therefore, the Google Maps Android Development Kit cannot be used on the remote control. If you must use Google Maps, you may consider using the JavaScript version so that the map is displayed on the remote control only through the network.
<br><p><em><small>°°°</small></em></p>
