### ISSUE TITLE
Automated Flight does not work in Restricted DJI Geo Zone

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#299]
Drone: Mavic 3 Enterprise
SDK: `5.8.0`

In dealing with DJI Geo Zones, it was discovered that we cannot execute automated flights within Restricted DJI Geo Zones despite unlocking them. Video of the flight is enclosed.

Location: 40.2520047150063, -111.7102850517554
LAANC Zone: Restricted Zones: Provo Muni

Automated flight issues start after the 1:30 mark. ~~Video (too large to include in the ticket)~~ Edit: Video uploaded below

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103741'>Zendesk ticket #103741</a>:<br><br>I'm sorry, but we are unable to open the link to Google Drive. Could you please verify if the Mobile SDK can obtain the unlock certificate for this region from the aircraft? After that, please try calling setFlyZoneLicensesEnabled to open this certificate before takeoff.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
We had obtained the unlock the certificate for the region. Our app doesn't allow takeoff without validating/enabling GeoZones/Licenses. Part of that process includes the user intentionally enabling the license for restricted zones (`FlyZoneManager.getInstance().setFlyZoneLicensesEnabled()` is the SDK call)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103741'>Zendesk ticket #103741</a>:<br><br>Would your logic require users to log in to their DJI account to apply for the certificate in that region? Since identity verification of current users will be conducted during the lifting of the ban, only logging into the corresponding DJI account will allow for a smooth lifting of the ban.
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
We are in the midst of verifying that, but manual flight in the Restricted zone works. It specifically fails when the automated flight tries to enter that same restricted.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103741'>Zendesk ticket #103741</a>:<br><br>Could you please upload the video you provided to us earlier to this address: https://pan-sec.djicorp.com/s/BtcQEttGeFgz59e? The password for the upload is dji123.
If you are already able to fly manually in the restricted zone, then the reason for the waypoint mission failure may not be the restricted zone. When the execution fails, did the health information or the task start interface provide any information?
<br><p><em><small>°°°</small></em></p>

**Comment by tkocik92** [comment]
Uploaded the video. We are not using any of the DJI UX widgets so I cannot say for sure nothing surfaced. For context, my `WaylineExecutingInfoListener` looks like this:

```
WaypointMissionManager.getInstance().addWaylineExecutingInfoListener(object : WaylineExecutingInfoListener {
           override fun onWaylineExecutingInfoUpdate(excutingWaylineInfo: WaylineExecutingInfo?) {
                // Do a bunch of reporting
           }

           override fun onWaylineExecutingInterruptReasonUpdate(error: IDJIError?) {
                    Log.e(TAG, "onWaylineExecutingInterruptReasonUpdate: $error") // Don't have access to this at the moment

                    if (error?.errorCode()?.contains("OBSTACLE") == true ||
                        error?.errorCode() == "LOW_LIMIT"
                    ) {
                        // Send some user-facing message as this is related to obstacle avoidance
                    }
                }
            })
```

As you'll see in the video, attempting to resume the waypoint mission does not throw an error (and that would surface to the user in our implementation).

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/103741'>Zendesk ticket #103741</a>:<br><br>Based on the video you submitted, it appears that the aircraft may have been unable to continue due to approaching its maximum flight altitude. Did you receive any error messages when starting the mission?

If there were no error messages, could you reproduce the issue once more and then export the aircraft logs for the time of the issue?

There are two ways to export the aircraft logs:


1. After reproducing the issue, restart the aircraft, connect it to DJI Assistant 2, go to log export, and select the corresponding logs for export.
2. After reproducing the issue, restart the aircraft, have the remote controller connected to the aircraft, use Pilot 2's log management feature, select the aircraft logs, and then upload the corresponding logs to our analysis platform. Please submit the uploaded QR code to us.
<br><p><em><small>°°°</small></em></p>
