### ISSUE TITLE
liveStream.isStreaming() on 300 RTK not working well

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#352]
Hi Dji,

On 300 RTK it happens that sometimes it returns true whereas nothing is streaming...

As a result if we code sthing based on the following condition :

`if (liveStream.isStreaming()) { then sthing }`

we might encounters some Bad behaviors..

Note: it happens after the stream has been running for a long time, and not very often... (rarely)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108775'>Zendesk ticket #108775</a>:<br><br>Could you please let us know which version of MSDK you are using and what live streaming protocol you are using? Is this question related to the sample code?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
MSDK v5 and RTMP, more globally this question is related to MSDK V5 over 300 RTK and RTMP.

We did no noticeable change on the sample code that could explain this kind of issue.

Regards,

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108775'>Zendesk ticket #108775</a>:<br><br>I would like to know the specific version of MSDK V5 that you are using.

When liveStream.isStreaming is true, it means the SDK is still attempting to push the stream. What exactly happens when you mention that the stream has not been triggered? Or how do you determine that the live stream has not been triggered?

It would be more helpful if there is a reliable method for us to identify it.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
1.5.8 

This bug is quite hard to reproduce, I had it once since now.

I will let you know if I get it another time.

And will close the issue otherwise.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108775'>Zendesk ticket #108775</a>:<br><br>I will wait for you to provide us with more information.
<br><p><em><small>°°°</small></em></p>
