### ISSUE TITLE
Using CameraKey.KeyThermalZoomRatiosRange returns values on DJI Mini 3 Pro

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#353]
Hi Dji,

CameraKey.KeyThermalZoomRatiosRange along with CameraIndex and lens returns, for Dji Mini 3 Pro: `[1,2,4]`

No thermal camera on this UAV, so no value expected here `null`

It happens at least when aircarft is disconnected;

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108808'>Zendesk ticket #108808</a>:<br><br>I have reproduced this issue and will submit it for analysis by the team.
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108808'>Zendesk ticket #108808</a>:<br><br>The issue has been fixed in version 5.10 alpha. You can check the release notes for that version and update to experience the fixes.
https://github.com/dji-sdk/Mobile-SDK-Android-V5/tree/dev-sdk-alpha
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Oh I see that crashes on Mini 3 and Mini 3 Pro for EU have been fixed too! will give it a try then ;)

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/108808'>Zendesk ticket #108808</a>:<br><br>If you encounter any issues during the testing process, feel free to reach out to us at any time.
<br><p><em><small>°°°</small></em></p>
