### ISSUE TITLE
Mini 3 Pro crash issue

### ISSUE THREAD

**Issue by antonymarion** [dji-sdk/Mobile-SDK-Android-V5#369]
Hi Dji,

![image](https://github.com/dji-sdk/Mobile-SDK-Android-V5/assets/8767496/c8237a23-26d7-417c-85e4-7ff7a5fe0680)

is the right snippet to put inside the DJIMainActivity kotlin file ?

`UASRemoteIDManager.getInstance().setUASRemoteIDAreaStrategy(AreaStrategy.US_STRATEGY)`

I tested with this, but I get some crash occasionnaly during startup...

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109703'>Zendesk ticket #109703</a>:<br><br>Could you provide us with your crash logs? Also, did you call setUASRemoteIDAreaStrategy after completing the init interface?
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Please provide the snippet code, and where it should be placed; it will ease the resolution and the investigation of the issue thk you

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/109703'>Zendesk ticket #109703</a>:<br><br>I think you can provide us with crash logs, so the crash you are experiencing may not be related to the crash caused by setUASRemoteIDAreaStrategy.

The function setUASRemoteIDAreaStrateg needs to be called after the onRegisterSuccess callback.
<br><p><em><small>°°°</small></em></p>

**Comment by antonymarion** [comment]
Crash on mini 3 Pro has been solved in last release
