### ISSUE TITLE
Core System Error with KeyHomeLocationUsingCurrentRemoteControllerLocation

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#37]
SDK version: `5.0.0`
Drone: M30
Drone Firmware: `V04.02.0000`

I am attempting to use `FlightControllerKey.KeyHomeLocationUsingCurrentRemoteControllerLocation` to update the return-to-home location. I am implementing it as shown:

```
fun returnToRC(controllerLocation: LatLng) {
    // To start a return-to-remote-controller, we first have to tell the SDK to user the
    // provided location as the go-home location
    keyManager.performAction(
        KeyTools.createKey(FlightControllerKey.KeyHomeLocationUsingCurrentRemoteControllerLocation),
        LocationCoordinate2D(controllerLocation.latitude, controllerLocation.longitude),
        object : CompletionCallbackWithParam<EmptyMsg> {
            override fun onSuccess(t: EmptyMsg?) {
                // Do something on success
            }

            override fun onFailure(error: IDJIError) {
                Log.e("DEBUGTAG", "Return to RC failed: ${error.errorCode()} - $error")
            }
        }
    )
}
```

Whenever I call this, whether the drone is on the ground or in the air, I get the following log:
`Return to RC failed: CORE_SYSTEM_ERROR - DJIError{errorCode='CORE_SYSTEM_ERROR', innerCode='', description='null', hint='error code = -7}`

What am I doing wrong? This particular key is not used in the sample app (Neither is the related `KeyHomeLocationUsingCurrentAircraftLocation`)

**Comment by DJI-William** [comment]
Most likely your GPS signal is bad or you have set your home location to far. I find out this key is very useless as you still need to input a coordinate to set the home location so there is no difference between this key and KeyHomeLocation. I suggest you call an Android API to retrieve your Android device's coordinate and set by calling KeyHomeLocation rather than this key. It will make the same effect, we will consider delete this KeyHomeLocationUsingCurrentRemoteControllerLocation.
