### ISSUE TITLE
Default Units for Obstacle Avoidance

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#52]
SDK Version: `5.1`

I am currently integrating obstacle avoidance reporting and would like clarification on the unit of the values being returned. Normally, any distance value is returned in meters. However, I have previously integrated `FlightControllerKey.KeyUltrasonicHeight` which explicitly returns it's values in decimeters (10 decimeters = 1 meter for those unaware). The keys I'm specifically curious about are `FlightAssistantKey.KeyUpwardsAvoidanceDistance` and `FlightAssistantKey.KeyDownwardsAvoidanceDistance`.

Normally I'd check the docs but `FlightAssistantKey` does not appear to be documented yet.

**Comment by DJI-William** [comment]
The FlightAssistantKey is encapsulated into Class IPerceptionManager because different aircraft uses different keys in obstacle avoidance. So we choose not to open the FlightAssistantKey. You can check perceptionManager.addObstacleDataListener and in the ruturn call ObstacleData.getUpwardObstacleDistance. Different aircraft may use different sensors so I cannot ensure the readings are in dm or m. I think you can easily find the answer in the test.

**Comment by tkocik92** [comment]
Adding this after the fact in the event anyone sees this later. The distances returned in `ObstacleData.getUpwardObstacleDistance` and the related methods are all in millimeters. Meanwhile, `PerceptionInfo. getUpwardObstacleAvoidanceWarningDistance` and the related methods return distances in meters.

Tested on the Mavic 3E

**Comment by DJI-William** [comment]
We will not change the unit for them. I will add the unit of doc.
