### ISSUE TITLE
Cannot take photos on Simulator

### ISSUE THREAD

**Issue by tkocik92** [dji-sdk/Mobile-SDK-Android-V5#84]
Drone: Mavic 3E
SDK: `5.2.0`
Drone Firmware: `06.01.0606`
RC Firmware: `02.00.0407`
DJI Assistant 2 Version: `2.1.5`

This has been an issue for some time and only effects the drone while using the simulator. If I attempt to take a photo using the hardware shutter button, nothing happens. If I attempt to take a photo using the SDK commands, I get the following error:

`ErrorImp{errorType='CORE', errorCode='CANNOT_START_TASK_ON_WEAK_GPS', innerCode='', description='null', hint='error code = -472'}`

I should note that I don't believe this problem exists on the M30.

I understand this is a problem that only exists on the simulator and therefore isn't that important, but it slows down app development. Is there any workaround available or a way to get this resolved?

**Comment by DJI-William** [comment]
Are you using Mac or Windows? I remember back in the old firmware, the SD card is not accessable beacause it is occupied by the Type-C cable by PC when you are using the DJI Assistant 2 simulator. I think that is why you cannot shoot photo, because the SD card is been used by the PC. An evidance of it is you can view the SD card content on PC. This issue is fixed in Windows DJI Assistant 2 simulator but not Mac.

**Comment by tkocik92** [comment]
Unfortunately I am on a Mac. Is there any estimate on when/if this would get fixed on Mac's DJI Assistant 2?

**Comment by DJI-William** [comment]
No estimated fix now, I suggest you use Windows DJI Assistant 2 now.

**Comment by dji-dev** [comment]
It is already available on Windows systems.
