### ISSUE TITLE
Smart Track Support

### ISSUE THREAD

**Issue by Marcello09** [dji-sdk/Mobile-SDK-Android-V5#95]
Previously on MSDK v4 it was available to use active track module. Having support for ~active~ smart track in this SDK would be greatly appreciated. 

April 4th Update: Sorry, I mean Smart Track feature.

**Comment by DJI-William** [comment]
It is a consumer firmware feature, normally it does not support on enterprise firmware. So there is no native active track feature on MSDK v5.

**Comment by Marcello09** [comment]
Hi Willian, 

I'm sorry, I refered to the wrong feature. What i meant was the Smart Track feature, present on M30 drones

**Comment by DJI-William** [comment]
Do you mean the spot light feature, the camera will follow the target while the aircraft stays stationary? This feature hasn't been implemented in MSDK v5 yet.

**Comment by Marcello09** [comment]
Yes, exactly this feature! 

Ok, I was looking for it and couldn't find it.

Is there a way for me to collaborate in getting this feature implemented?

**Comment by DJI-William** [comment]
You can receive the video stream, you can rotate the gimbal. So you can develop by yourself be writing gimbal rotation algorithm according to the video stream.

**Comment by shaji-Dev** [comment]
Hi, any update on this feature yet? 

Smart Tracking Manager was announced as an upcoming feature since 5.6.0 on 2023.09.18 (https://developer.dji.com/doc/mobile-sdk-tutorial/en/)

![image](https://github.com/user-attachments/assets/1075c091-25ec-4435-bc50-ee1a2309f03b)

I also see in the `HSIView` in `uxsdk` all the smart track attributes but they're not used yet

```
    <declare-styleable name="HSIView">
        <attr name="uxsdk_hsi_smart_track_point_marker_size" format="dimension" />
        <attr name="uxsdk_hsi_smart_track_point_marker" format="reference" />
        <attr name="uxsdk_hsi_smart_track_point_marker_text_color" format="color" />
        <attr name="uxsdk_hsi_smart_track_enable" format="boolean" />
        ...
    </declare-styleable>
```


We don't want to implement it ourselves if it's being worked on already and is out soon.

Thank you.
